<!-- BEGIN CORE PLUGINS -->
{!!Html::script(asset('admin/assets/global/plugins/jquery.min.js'))!!}
{!!Html::script(asset('admin/assets/global/plugins/bootstrap/js/bootstrap.min.js'))!!}
{!!Html::script(asset('admin/assets/global/plugins/js.cookie.min.js'))!!}
{!!Html::script(asset('admin/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js'))!!}
{!!Html::script(asset('admin/assets/global/plugins/jquery.blockui.min.js'))!!}
{!!Html::script(asset('admin/assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js'))!!}
{!!Html::script(asset('admin/assets/global/plugins/moment.min.js'))!!}
{!!Html::script(asset('admin/assets/global/scripts/datatable.js'))!!}
{!!Html::script(asset('admin/assets/global/plugins/datatables/datatables.min.js'))!!}
{!!Html::script(asset('admin/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js'))!!}
{!!Html::script(asset('admin/assets/global/plugins/bootstrap-daterangepicker/daterangepicker.min.js'))!!}
{!!Html::script(asset('admin/assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js'))!!}
{!!Html::script(asset('admin/assets/global/plugins/morris/morris.min.js'))!!}
{!!Html::script(asset('admin/assets/global/plugins/select2/js/select2.full.min.js'))!!}
{!!Html::script(asset('admin/assets/global/plugins/morris/raphael-min.js'))!!}
{!!Html::script(asset('admin/assets/global/plugins/counterup/jquery.waypoints.min.js'))!!}
{!!Html::script(asset('admin/assets/global/plugins/counterup/jquery.counterup.min.js'))!!}
{!!Html::script(asset('admin/assets/global/plugins/amcharts/amcharts/amcharts.js'))!!}
{!!Html::script(asset('admin/assets/global/plugins/amcharts/amcharts/serial.js'))!!}
{!!Html::script(asset('admin/assets/global/plugins/amcharts/amcharts/pie.js'))!!}
{!!Html::script(asset('admin/assets/global/plugins/amcharts/amcharts/radar.js'))!!}
{!!Html::script(asset('admin/assets/global/plugins/amcharts/amcharts/themes/light.js'))!!}
{!!Html::script(asset('admin/assets/global/plugins/amcharts/amcharts/themes/patterns.js'))!!}
{!!Html::script(asset('admin/assets/global/plugins/amcharts/amcharts/themes/chalk.js'))!!}
{!!Html::script(asset('admin/assets/global/plugins/amcharts/ammap/ammap.js'))!!}
{!!Html::script(asset('admin/assets/global/plugins/amcharts/ammap/maps/js/worldLow.js'))!!}
{!!Html::script(asset('admin/assets/global/plugins/amcharts/amstockcharts/amstock.js'))!!}
{!!Html::script(asset('admin/assets/global/plugins/fullcalendar/fullcalendar.min.js'))!!}
{!!Html::script(asset('admin/assets/global/plugins/horizontal-timeline/horizontal-timeline.js'))!!}
{!!Html::script(asset('admin/assets/global/plugins/flot/jquery.flot.min.js'))!!}
{!!Html::script(asset('admin/assets/global/plugins/flot/jquery.flot.resize.min.js'))!!}
{!!Html::script(asset('admin/assets/global/plugins/flot/jquery.flot.categories.min.js'))!!}
{!!Html::script(asset('admin/assets/global/plugins/jquery-easypiechart/jquery.easypiechart.min.js'))!!}
{!!Html::script(asset('admin/assets/global/plugins/jquery.sparkline.min.js'))!!}
{!!Html::script(asset('admin/assets/global/scripts/app.min.js'))!!}
{!!Html::script(asset('admin/assets/pages/scripts/table-datatables-ajax.min.js'))!!}
{!!Html::script(asset('admin/assets/pages/scripts/components-select2.min.js'))!!}
{!!Html::script(asset('admin/assets/pages/scripts/dashboard.min.js'))!!}
{!!Html::script(asset('admin/assets/layouts/layout/scripts/layout.min.js'))!!}
{!!Html::script(asset('admin/assets/layouts/layout/scripts/demo.min.js'))!!}
{!!Html::script(asset('admin/assets/layouts/global/scripts/quick-sidebar.min.js'))!!}
{!!Html::script(asset('admin/assets/layouts/global/scripts/quick-nav.min.js'))!!}
{!!Html::script(asset('admin/js/actions.js'))!!}
{!!Html::script(asset('//cdn.ckeditor.com/4.6.2/full/ckeditor.js'))!!}
{!!Html::script(asset('//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js'))!!}
{!!Html::script(asset('https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js'))!!}
{!!Html::script(asset('https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.4.0/bootbox.min.js'))!!}

@yield('scripts')